# Generated by Django 4.1.1 on 2022-09-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Urls",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("long_url", models.URLField()),
                ("short_url", models.CharField(blank=True, max_length=15, unique=True)),
                ("pub_date", models.DateTimeField(auto_now=True)),
                ("count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["-pub_date"],
            },
        ),
    ]
